-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 07:26:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema customers_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema customers_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `customers_database` DEFAULT CHARACTER SET utf8 ;
USE `customers_database` ;

-- -----------------------------------------------------
-- Table `customers_database`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`accounts` (
  `uuid` VARCHAR(36) NOT NULL,
  `account_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `account_name_UNIQUE` (`account_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`units_save`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`units_save` (
  `uuid` VARCHAR(36) NOT NULL,
  `unit` VARCHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `unit_UNIQUE` (`unit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`materials` (
  `uuid` VARCHAR(36) NOT NULL,
  `material` VARCHAR(100) NULL DEFAULT NULL,
  `unit` VARCHAR(6) NULL DEFAULT NULL,
  `sort_num` INT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`daily_prices_datetime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`daily_prices_datetime` (
  `uuid` VARCHAR(36) NOT NULL,
  `prices_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`daily_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`daily_prices` (
  `uuid` VARCHAR(36) NOT NULL,
  `price` REAL NULL DEFAULT NULL,
  `materials_uuid` VARCHAR(36) NOT NULL,
  `daily_prices_datetime_uuid` VARCHAR(36) NOT NULL,
  `material_sort` INT NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_daily_prices_materials_idx` (`materials_uuid` ASC) VISIBLE,
  INDEX `fk_daily_prices_daily_prices_datetime1_idx` (`daily_prices_datetime_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_daily_prices_materials`
    FOREIGN KEY (`materials_uuid`)
    REFERENCES `customers_database`.`materials` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_prices_daily_prices_datetime1`
    FOREIGN KEY (`daily_prices_datetime_uuid`)
    REFERENCES `customers_database`.`daily_prices_datetime` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`booking_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`booking_actions` (
  `uuid` VARCHAR(36) NOT NULL,
  `action_name` VARCHAR(200) NULL DEFAULT NULL,
  `action_time` DATETIME NOT NULL,
  `action_completed` TINYINT(4) NULL DEFAULT NULL,
  `accounts_uuid` VARCHAR(36) NOT NULL,
  `booking_notice` TEXT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_booking_actions_accounts1_idx` (`accounts_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_booking_actions_accounts1`
    FOREIGN KEY (`accounts_uuid`)
    REFERENCES `customers_database`.`accounts` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`booking_action_pos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`booking_action_pos` (
  `uuid` VARCHAR(36) NOT NULL,
  `booking_value` REAL NULL DEFAULT NULL,
  `price` REAL NULL DEFAULT NULL,
  `booking_datetime` DATETIME NOT NULL,
  `materials_uuid` VARCHAR(36) NOT NULL,
  `booking_actions_uuid` VARCHAR(36) NOT NULL,
  `booking_pos_sort` INT NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_bookings_materials1_idx` (`materials_uuid` ASC) VISIBLE,
  INDEX `fk_bookings_booking_actions1_idx` (`booking_actions_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_materials100`
    FOREIGN KEY (`materials_uuid`)
    REFERENCES `customers_database`.`materials` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_booking_actions100`
    FOREIGN KEY (`booking_actions_uuid`)
    REFERENCES `customers_database`.`booking_actions` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`bookings` (
  `uuid` VARCHAR(36) NOT NULL,
  `booking_value` REAL NULL DEFAULT NULL,
  `price` REAL NULL DEFAULT NULL,
  `booking_datetime` DATETIME NOT NULL,
  `materials_uuid` VARCHAR(36) NOT NULL,
  `accounts_uuid` VARCHAR(36) NOT NULL,
  `current_status` REAL NULL DEFAULT NULL,
  `is_last_booking` TINYINT NULL,
  `bookings_action_pos_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_bookings_materials1_idx` (`materials_uuid` ASC) VISIBLE,
  INDEX `fk_bookings_accounts1_idx` (`accounts_uuid` ASC) VISIBLE,
  INDEX `fk_bookings_bookings_action_pos1_idx` (`bookings_action_pos_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_materials1`
    FOREIGN KEY (`materials_uuid`)
    REFERENCES `customers_database`.`materials` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_accounts1`
    FOREIGN KEY (`accounts_uuid`)
    REFERENCES `customers_database`.`accounts` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_bookings_action_pos1`
    FOREIGN KEY (`bookings_action_pos_uuid`)
    REFERENCES `customers_database`.`booking_action_pos` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`bookings_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`bookings_notes` (
  `uuid` VARCHAR(36) NOT NULL,
  `note_value` REAL NULL DEFAULT NULL,
  `price` REAL NULL DEFAULT NULL,
  `note_datetime` DATETIME NOT NULL,
  `materials_uuid` VARCHAR(36) NOT NULL,
  `accounts_uuid` VARCHAR(36) NOT NULL,
  `bookings_action_pos_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_bookings_materials1_idx` (`materials_uuid` ASC) VISIBLE,
  INDEX `fk_bookings_accounts1_idx` (`accounts_uuid` ASC) VISIBLE,
  INDEX `fk_bookings_notes_bookings_action_pos1_idx` (`bookings_action_pos_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_materials10`
    FOREIGN KEY (`materials_uuid`)
    REFERENCES `customers_database`.`materials` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_accounts10`
    FOREIGN KEY (`accounts_uuid`)
    REFERENCES `customers_database`.`accounts` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_notes_bookings_action_pos1`
    FOREIGN KEY (`bookings_action_pos_uuid`)
    REFERENCES `customers_database`.`booking_action_pos` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`generell_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`generell_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value_key` VARCHAR(30) NULL,
  `gen_value` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`booking_action_imgs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`booking_action_imgs` (
  `uuid` VARCHAR(36) NOT NULL,
  `booking_img` BLOB NULL,
  `booking_imgtype` VARCHAR(20) NULL,
  `booking_actions_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_booking_action_imgs_booking_actions1_idx` (`booking_actions_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_booking_action_imgs_booking_actions1`
    FOREIGN KEY (`booking_actions_uuid`)
    REFERENCES `customers_database`.`booking_actions` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customers_database`.`booking_actions_uebertrag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customers_database`.`booking_actions_uebertrag` (
  `uuid` VARCHAR(36) NOT NULL,
  `booking_prime_uuid` VARCHAR(36) NOT NULL,
  `booking_second_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_booking_actions_uebertrag_booking_actions1_idx` (`booking_prime_uuid` ASC) VISIBLE,
  INDEX `fk_booking_actions_uebertrag_booking_actions2_idx` (`booking_second_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_booking_actions_uebertrag_booking_actions1`
    FOREIGN KEY (`booking_prime_uuid`)
    REFERENCES `customers_database`.`booking_actions` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_actions_uebertrag_booking_actions2`
    FOREIGN KEY (`booking_second_uuid`)
    REFERENCES `customers_database`.`booking_actions` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `customers_database`.`generell_values`
-- -----------------------------------------------------
START TRANSACTION;
USE `customers_database`;
INSERT INTO `customers_database`.`generell_values` (`id`, `value_key`, `gen_value`) VALUES (DEFAULT, 'currency', '$');

COMMIT;

