-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 20:53:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easyraw_userdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyraw_userdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyraw_userdatabase` DEFAULT CHARACTER SET utf8 ;
USE `easyraw_userdatabase` ;

-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`er_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`er_companies` (
  `er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_creationdatetime` DATETIME NULL,
  `er_name` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_address` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_zip` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_city` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`er_uuid`),
  UNIQUE INDEX `er_uuid_UNIQUE` (`er_uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`rmm_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`rmm_users` (
  `er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_companies_er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_creationdatetime` DATETIME NULL,
  `er_email` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_password` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_user_emailconfirmation_succeed` TINYINT(4) NULL,
  PRIMARY KEY (`er_uuid`),
  INDEX `fk_rmm_users_er_companies_idx` (`er_companies_er_uuid` ASC) VISIBLE,
  UNIQUE INDEX `er_uuid_UNIQUE` (`er_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_rmm_users_er_companies`
    FOREIGN KEY (`er_companies_er_uuid`)
    REFERENCES `easyraw_userdatabase`.`er_companies` (`er_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`er_session_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`er_session_token` (
  `er_uuid` INT NOT NULL,
  `rmm_users_er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_token_datetime` DATETIME NULL,
  `er_session_token` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`er_uuid`),
  INDEX `fk_er_session_token_rmm_users1_idx` (`rmm_users_er_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_er_session_token_rmm_users1`
    FOREIGN KEY (`rmm_users_er_uuid`)
    REFERENCES `easyraw_userdatabase`.`rmm_users` (`er_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
