-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 19:58:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easyraw_userdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyraw_userdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyraw_userdatabase` DEFAULT CHARACTER SET utf8 ;
USE `easyraw_userdatabase` ;

-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`er_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`er_companies` (
  `er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_creationdatetime` DATETIME NULL,
  `er_name` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_address` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_zip` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_city` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`er_uuid`),
  UNIQUE INDEX `er_uuid_UNIQUE` (`er_uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`er_user_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`er_user_logins` (
  `er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_companies_er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `er_creationdatetime` DATETIME NULL,
  `er_email` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_password` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_user_emailconfirmation_succeed` TINYINT(4) NULL,
  PRIMARY KEY (`er_uuid`),
  INDEX `fk_rmm_users_er_companies_idx` (`er_companies_er_uuid` ASC),
  UNIQUE INDEX `er_uuid_UNIQUE` (`er_uuid` ASC),
  CONSTRAINT `fk_rmm_users_er_companies`
    FOREIGN KEY (`er_companies_er_uuid`)
    REFERENCES `easyraw_userdatabase`.`er_companies` (`er_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyraw_userdatabase`.`er_session_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyraw_userdatabase`.`er_session_token` (
  `er_uuid` INT NOT NULL,
  `er_token_datetime` DATETIME NULL,
  `er_session_token` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `er_user_logins_er_uuid` VARCHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`er_uuid`),
  INDEX `fk_er_session_token_er_user_logins1_idx` (`er_user_logins_er_uuid` ASC),
  CONSTRAINT `fk_er_session_token_er_user_logins1`
    FOREIGN KEY (`er_user_logins_er_uuid`)
    REFERENCES `easyraw_userdatabase`.`er_user_logins` (`er_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
